require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "Xamarin.Labs.Robotics-1.0.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Robotics from Xamarin.Labs" \
		--summary="Communicate with Robotics projects." \
		--publisher="Xamarin Inc." \
		--website="https://github.com/xamarin/Xamarin.Labs-Robotics" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/Xamarin.Labs.Robotics_128x128.png" \
		--icon="icons/Xamarin.Labs.Robotics_512x512.png" \
		--library="ios":"bin/Robotics.Mobile.Core.iOS/Robotics.Mobile.Core.iOS.dll" \
		--library="android":"bin/Robotics.Mobile.Core.Droid/Robotics.Mobile.Core.Droid.dll" \
		--sample="iOS Sample. Demonstrates Awesomeness on iOS.":"samples/SampleDoesNotExist.sln" \
		--sample="Android Sample. Demonstrates Awesomeness on Android":"samples/SampleDoesNotExist.sln"
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
