require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "Monkey.Robotics-0.5.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Monkey.Robotics" \
		--summary="Create robotic projects and integrate them with Xamarin apps." \
		--publisher="Xamarin Inc." \
		--website="https://github.com/xamarin/Xamarin.Labs-Robotics" \
		--src-url="https://github.com/xamarin/Monkey.Robotics/tree/master/Source" \
		--publisher-url="http://xamarin.com" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/Monkey.Robotics_128x128.png" \
		--icon="icons/Monkey.Robotics_512x512.png" \
		--library="ios":"bin/Robotics.Mobile.Core.iOS/Robotics.Mobile.Core.dll" \
		--library="ios":"bin/Robotics.Mobile.Core.iOS/Robotics.Mobile.Core.iOS.dll" \
		--library="ios":"bin/Robotics.Mobile.Core.iOS/Newtonsoft.Json.dll" \
		--library="android":"bin/Robotics.Mobile.Core.Droid/Robotics.Mobile.Core.dll" \
		--library="android":"bin/Robotics.Mobile.Core.Droid/Robotics.Mobile.Core.Droid.dll" \
		--library="android":"bin/Robotics.Mobile.Core.Droid/Newtonsoft.Json.dll" \
		--sample="Netduino .NET MF Sample - Onboard LED blinking. A simple micro framework project that blinks the onboard LED on a Netduino.":"../../Sample Apps/NetduinoBlink/NetduinoBlink.sln" \
		--sample="Netduino .NET MF Sample - Button Press. A simple micro framework project that lights the onboard LED when the onboard button is pressed.":"../../Sample Apps/ButtonPush/ButtonPush.sln" \
		#--monodoc="../../API Docs"
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
