#region License
// Copyright (c) 2014, David Taylor
//
// Permission to use, copy, modify, and/or distribute this software for any 
// purpose with or without fee is hereby granted, provided that the above 
// copyright notice and this permission notice appear in all copies, unless 
// such copies are solely in the form of machine-executable object code 
// generated by a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES 
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF 
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR 
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN 
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF 
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#endregion License
using System;

namespace Robotics.Serialization
{
	internal static class PortableBinaryToken
	{
		// NOTE: Token values must be negative to avoid conflicts with property and length values
		internal const int StartObjectToken = ~'{' | 0x40; // -0x3c;
		internal const int EndObjectToken = ~'}' | 0x40; // -0x3e;
		internal const int StartArrayToken = ~'[' | 0x40; // -0x1c;
		internal const int EndArrayToken = ~']' | 0x40; // -0x1e;
		internal const int NullValueToken = ~'~' | 0x40; // -0x3f;
		internal const int TrueValueToken = ~'t' | 0x40; // -0x35;
		internal const int FalseValueToken = ~'f' | 0x40; // -0x27;
	}
}
