#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.Robotics.BluetoothLEExplorer.Droid.Resource", IsApplication=true)]

namespace Xamarin.Robotics.BluetoothLEExplorer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Robotics.Core.Resource.String.library_name = global::Xamarin.Robotics.BluetoothLEExplorer.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int AddressText = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int CharacteristicDataTypeText = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int CharacteristicIDText = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int CharacteristicListView = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int CharacteristicNameText = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int CharacteristicPropertiesText = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int DeviceAddressText = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int DeviceNameText = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int DevicesListView = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int RawValueText = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int RssiText = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int ScanButton = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int ServiceIDText = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int ServiceListView = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int ServiceNameText = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int ServiceTypeText = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int ServiceUuidText = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int StringValueText = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ValueUdpatedDateTime = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int textView1 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CharacteristicDetailScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CharacteristicListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CharacteristicListScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DeviceListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScannerHome = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ServiceListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ServiceListScreen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
